[package]
name = "shamir"
type = "contract"
authors = ["Elena Fuentes"]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.19.0", directory="yarn-project/aztec-nr/aztec" }
field_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.19.0", directory="yarn-project/aztec-nr/field-note" }
